//==================================================
//     Outputs that match the input variables
//==================================================
output "repository_roles" {
  description = "The value of the `repository_roles` input variable, or the default value if the input was `null` or wasn't provided."
  value       = var.repository_roles
}
output "add_unique_suffix_to_role_names" {
  description = "The value of the `add_unique_suffix_to_role_names` input variable, or the default value if the input was `null` or wasn't provided."
  value       = var.add_unique_suffix_to_role_names
}
output "add_unique_suffix_to_policy_names" {
  description = "The value of the `add_unique_suffix_to_policy_names` input variable, or the default value if the input was `null` or wasn't provided."
  value       = var.add_unique_suffix_to_policy_names
}

//==================================================
//       Outputs generated by this module
//==================================================
output "iam_oidc_provider_arn" {
  description = "The ARN of the `aws_iam_openid_connect_provider` resource that was either created in this module, or passed into this module."
  value       = local.oidc_provider.arn
}

output "iam_roles" {
  description = "A map of role names to `aws_iam_role` resources."
  value = {
    for role in aws_iam_role.this :
    role.name => role
  }
}
