//==================================================
//     Outputs that match the input variables
//==================================================
output "audience" {
  description = "The value of the `audience` input variable."
  value       = var.audience
}

//==================================================
//       Outputs generated by this module
//==================================================
output "oidc_host" {
  description = "The OIDC host that the IAM OIDC provider trusts."
  value       = local.oidc_host
}

output "oidc_provider" {
  description = "The IAM OIDC provider that was created."
  value       = aws_iam_openid_connect_provider.github_oidc
}
